### ISSUE TITLE
GCC > 13 compilation error

### ISSUE THREAD

**Issue by nebularnoise** [rollbear/dry-comparisons#8]
The library no longer compiles with GCC > 13.

Here's a minimum reproducible example

```cpp
#include "dry-comparisons.hpp"
#include <cstdio>

enum class E{
    Foo,
    Bar,
    Baz
};

int main(){
    using enum E;
    E e = Foo;

    if(e == rollbear::any_of{Foo})
    {
        puts("Starts with F!");
    }
    if(e == rollbear::any_of{Bar, Baz})
    {
        puts("Starts with B!");
    }
}
```

Compiler Explorer:
https://godbolt.org/z/qrf47oP1h

This might be related to GCC13 implementing [P2468R2](https://www.open-std.org/jtc1/sc22/wg21/docs/papers/2022/p2468r2.html), instead of an GCC-specific tiebreaker, still used in GCC 12 (iirc, reversed operator is considered worse).

**Comment by rollbear** [comment]
I see. Thanks. I'll have a look.

**Comment by rollbear** [comment]
Have a look at branch [break_recursion](https://github.com/rollbear/dry-comparisons/tree/break_recursion) and let me know if there are remaining issues.

**Comment by nebularnoise** [comment]
It seems to work wonderfully. Thanks a lot !

**Comment by rollbear** [comment]
Merged to main.
